server:
  port: 8284
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./app
    username:
    password:
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG